services:
  api:
    build:
      dockerfile: ./apps/api/Dockerfile
      target: development
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    command: npm run start:dev api
    ports:
      - ${PORT}:${PORT}

  currency-rates-importer:
    build:
      dockerfile: ./apps/currency-rates-importer/Dockerfile
      target: development
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    command: npm run start:dev currency-rates-importer

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/mt_nestjs:/var/lib/postgresql/data
