services:
  api:
    build:
      dockerfile: ./apps/api/Dockerfile
      target: dev
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    command: npm run start:dev api
    ports:
      - ${API_PORT}:${API_PORT}

  currency-rates-importer:
    build:
      dockerfile: ./apps/currency-rates-importer/Dockerfile
      target: dev
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    command: npm run start:dev currency-rates-importer

  operations-import-handler:
    build:
      dockerfile: ./apps/operations-import-handler/Dockerfile
      target: dev
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      RABBITMQ_URL: 'amqp://admin:admin@rabbitmq:5672'
      RABBITMQ_OPERATIONS_IMPORT_QUEUE: 'operations_import'
    depends_on:
      - db
    command: npm run start:dev operations-import-handler
    ports:
      - ${OPERATION_IMPORT_HANDLER_PORT}:${OPERATION_IMPORT_HANDLER_PORT}

  operations-import-consumer:
    build:
      dockerfile: ./apps/operations-import-consumer/Dockerfile
      target: dev
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      RABBITMQ_URL: 'amqp://admin:admin@rabbitmq:5672'
      RABBITMQ_OPERATIONS_IMPORT_QUEUE: 'operations_import'
    depends_on:
      - db
    command: npm run start:dev operations-import-consumer

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/mt_nestjs:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
