apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: ft
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: api
#          image: fintrack-api:latest
          image: fintrackregistry.azurecr.io/fintrack-api:latest
          ports:
            - containerPort: 3000
#          imagePullPolicy: Never
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: DATABASE_URL
            - name: API_PORT
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: API_PORT
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: API_URL
            - name: JWT_USER_EMAILS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_USER_EMAILS_TOKEN_SECRET
            - name: JWT_USER_EMAILS_TOKEN_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_USER_EMAILS_TOKEN_EXPIRATION_TIME
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: EMAIL_HOST
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: EMAIL_PASSWORD
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: EMAIL_FROM
            - name: JWT_AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_AT_SECRET
            - name: JWT_AT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_AT_EXPIRATION_TIME
            - name: JWT_RT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_RT_SECRET
            - name: JWT_RT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_RT_EXPIRATION_TIME
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: RABBITMQ_URL
            - name: RABBITMQ_OPERATIONS_IMPORT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: RABBITMQ_OPERATIONS_IMPORT_QUEUE
            - name:   AZURE_BLOB_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key:   AZURE_BLOB_STORAGE_CONNECTION_STRING
            - name: OPERATIONS_IMPORT_AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: OPERATIONS_IMPORT_AZURE_CONTAINER_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ft
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: fintrack-api
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

