apiVersion: apps/v1
kind: Deployment
metadata:
  name: operations-import-consumer-deployment
  labels:
    app: operations-import-consumer
  namespace: ft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operations-import-consumer
  template:
    metadata:
      labels:
        app: operations-import-consumer
    spec:
      containers:
        - name: operations-import-consumer
#          image: fintrackregistry.azurecr.io/fintrack-operations-import-consumer:latest
          image: fintrack-operations-import-consumer:latest
#          imagePullPolicy: Always
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: operations-import-consumer-env
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: operations-import-consumer-env
                  key: RABBITMQ_URL
            - name: RABBITMQ_OPERATIONS_IMPORT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: operations-import-consumer-env
                  key: RABBITMQ_OPERATIONS_IMPORT_QUEUE
            - name: AZURE_BLOB_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: operations-import-consumer-env
                  key: AZURE_BLOB_STORAGE_CONNECTION_STRING
            - name: OPERATIONS_IMPORT_AZURE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: operations-import-consumer-env
                  key: OPERATIONS_IMPORT_AZURE_CONTAINER_NAME