apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: currency-rates-importer-env
  namespace: ft
spec:
  encryptedData:
    DATABASE_URL: AgB8KTSlvfYQywlAoidPwji2J6+l2j8IXJgeCI+LgfM30wL9mzu3O2kPw5GjMgBqVs1Vk8ARXALONtV5iwx1gvLDGZS+dOiUzSYtXQQItwsR0bC+viYvkm8cfrEyVlK+Z3mHvlcc/70N40qkvvKwXCjQPa2Fd+PTCJ401TWKKnxRe/s1Hq+XSuv3Qrlwu6rheDV7CrEY6s5VNXksVRwgpn4Dtm082A8nt/yBVmTGfWslWUkGqWM7XMzX+6oCGXv6thx1XXS+ckux49sRdfcXwBk1pAFBKARXbYeWo7oqRpxZHgfBRxOsrILn8DncHxQeCFOA80t+o3cN79nzsQJQw0rfsNoExHZGXvAwvoWhdaKERSCpUp/UVqrVq4SV6g5fGtik88lUxtjXm8ycDo67XQMTrgPMdtvcgv8BmxBP2mT3XNOd48LsXxU4xA12zU0xZFea3PKppSP5KcjjMRnXEtjjpV7NUxGu0mKGjsW2vc1Ae7EYra9A7Nh3JrtzmscCJT71mb28ePuljV+Fgu6IW54yzLdqoLmnKUZMLqWNYXrBv+o+H58lGR0fRtm185QLfn603uvvjHUbUAzl8muK519JH5YcB8UaAo28tBJ4NxRx5+nW9Y3NhVQU0c6zICFRnz1i5sg2Q0LpR2DNdJ7SEgSR5DasTMJKAf9JLcMR6d+cuRPtQf9D89CTbynR/dyGHTcl/eknlpvuyvSnqamzYfMfxAjvwwzsKKnyq1DLUkfowC4dZ9ehedWvyhV2kzO/vTmk84ua2gI7CNGxmF+orVmPnIiETz2lbQ+OI9/AwHbv9nJcdB6gJwRkpAmQNJmRTR0Fegx+kiCPAwYwfrzN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: currency-rates-importer-env
      namespace: ft
    type: Opaque

