on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  build:
    name: Build microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push docker images

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

#      - name: Build and push api
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.ACR_ENDPOINT }}/fintrack-api:latest
#          file: ./apps/api/Dockerfile
#          target: prod
#
      - name: Build and push currency-rates-importer
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/fintrack-currency-rates-importer:latest
          file: ./apps/currency-rates-importer/Dockerfile
          target: prod
#
#      - name: Build and push operations-import-consumer
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.ACR_ENDPOINT }}/fintrack-operations-import-consumer:latest
#          file: ./apps/operations-import-consumer/Dockerfile
#          target: prod

      # Deploy to Kubernetes

#      - name: 'Az CLI login'
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

#      - name: Azure CLI script
#        uses: azure/CLI@v1
#        with:
#          azcliversion: 2.30.0
#          inlineScript: |
#            az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_KUBERNETES_SERVICE }} --file $GITHUB_WORKSPACE/.kubeconfig
      #            az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_KUBERNETES_SERVICE }} --file $GITHUB_WORKSPACE/.kubeconfig

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

#      - name: Cat config
#        run: sudo mkdir ~/.kube && sudo cp $GITHUB_WORKSPACE/.kubeconfig ~/.kube/config

#      - name: Bash
#        run: whoami && sudo ls -la /home/runner && sudo ls -la /home/runner/.azure
#
      - name: Permissions
        run: sudo chown -R $USER:$USER /home/runner/.azure
#


      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v2
        with:
          resource-group: FinTrack-rg
          cluster-name: fintrack-aks
          admin: true

#      - name: Deploy API to AKS
#        id: deploy-aks
#        uses: Azure/k8s-deploy@v4
#        with:
#          namespace: 'ft'
#          manifests: |
#            k8s/api/02-deployment.yaml
#          images: ${{ secrets.ACR_ENDPOINT }}/fintrack-api:latest

      - name: Deploy currency-rates-importer to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'ft'
          manifests: |
            k8s/currency-rates-importer/02-deployment.yaml
          images: ${{ secrets.ACR_ENDPOINT }}/fintrack-currency-rates-importer:latest


#      - name: Restart AKS deployments
#        run: |
#          sudo kubectl config view
#          sudo kubectl get nodes -o wide
##          sudo kubectl rollout restart deployment api-deployment -n ft
##          sudo kubectl rollout restart deployment currency-rates-importer-deployment -n ft
##          sudo kubectl rollout restart deployment operations-import-consumer-deployment -n ft
